### ISSUE TITLE
Don't we support positional arguments now? 

### ISSUE THREAD

**Issue by IttayEyal** [IttayEyal/memoization#28]
https://github.com/IttayEyal/memoization/blob/12aba2e0a4327f6b28f08c7df935de3a5529edd2/memoize/memoized.py#L64

**Comment by adamatan** [comment]
Yes, we do:

https://github.com/IttayEyal/memoization/blob/12aba2e0a4327f6b28f08c7df935de3a5529edd2/test.py#L52
